import React, { useState } from 'react';
import { Sparkles, Check, CheckSquare, Square, Copy } from 'lucide-react';

interface AiResolutionBoxProps {
  stepsJson?: string;
  categoryName?: string;
  severity?: string;
}

export const AiResolutionBox: React.FC<AiResolutionBoxProps> = ({ stepsJson, categoryName, severity }) => {
  const [completedSteps, setCompletedSteps] = useState<Record<number, boolean>>({});
  const [copied, setCopied] = useState(false);

  let steps: string[] = [];
  try {
    if (stepsJson) {
      const parsed = JSON.parse(stepsJson);
      if (Array.isArray(parsed)) steps = parsed;
      else if (typeof parsed === 'string') steps = [parsed];
    }
  } catch {
    if (stepsJson) steps = stepsJson.split('\n').filter(Boolean);
  }

  if (steps.length === 0) {
    steps = [
      'Investigate system event viewer logs for fatal exception codes.',
      'Check peripheral connections, IP network routing, and authentication credentials.',
      'Restart the affected service or dispatch IT support engineer.',
    ];
  }

  const toggleStep = (idx: number) => {
    setCompletedSteps((prev) => ({ ...prev, [idx]: !prev[idx] }));
  };

  const handleCopy = () => {
    const text = steps.map((s, i) => `${i + 1}. ${s}`).join('\n');
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="rounded-lg border-2 border-[#0D9488] bg-teal-50/40 p-5 shadow-xs">
      <div className="flex items-center justify-between pb-3 border-b border-teal-200">
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-[#0D9488] text-white rounded-md">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-teal-950 flex items-center gap-2">
              Gemini AI Incident Diagnosis & Resolution
              <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 bg-teal-100 text-[#0D9488] rounded-full border border-teal-300">
                Auto-Classified
              </span>
            </h3>
            <p className="text-xs text-teal-800">
              Recommended remediation protocol generated by IncidentIQ AI triage
            </p>
          </div>
        </div>

        <button
          onClick={handleCopy}
          className="inline-flex items-center gap-1 text-xs font-semibold text-teal-800 hover:text-teal-950 bg-white border border-teal-300 px-2.5 py-1 rounded shadow-xs hover:bg-teal-50 transition-colors"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-teal-600" /> Copied!
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5 text-teal-600" /> Copy Steps
            </>
          )}
        </button>
      </div>

      {(categoryName || severity) && (
        <div className="mt-3 flex items-center gap-3 text-xs text-teal-900 bg-white/70 px-3 py-1.5 rounded border border-teal-200">
          {categoryName && (
            <span>
              Target Domain: <strong className="text-teal-950">{categoryName}</strong>
            </span>
          )}
          {severity && (
            <span>
              Calculated Urgency: <strong className="text-teal-950">{severity}</strong>
            </span>
          )}
        </div>
      )}

      <div className="mt-4 space-y-2.5">
        <p className="text-xs font-semibold uppercase tracking-wider text-teal-900">
          Actionable Troubleshooting Checklist:
        </p>
        <ul className="space-y-2">
          {steps.map((step, idx) => {
            const isDone = !!completedSteps[idx];
            return (
              <li
                key={idx}
                onClick={() => toggleStep(idx)}
                className={`flex items-start gap-2.5 p-2 rounded cursor-pointer transition-colors text-sm ${
                  isDone
                    ? 'bg-emerald-50 text-slate-500 line-through'
                    : 'bg-white text-slate-800 hover:bg-teal-50/80 shadow-2xs border border-teal-100'
                }`}
              >
                <button
                  type="button"
                  className="mt-0.5 text-teal-700 shrink-0 focus:outline-hidden"
                >
                  {isDone ? (
                    <CheckSquare className="w-4 h-4 text-emerald-600" />
                  ) : (
                    <Square className="w-4 h-4 text-slate-400" />
                  )}
                </button>
                <span className="font-mono text-xs leading-relaxed">{step}</span>
              </li>
            );
          })}
        </ul>
      </div>
    </div>
  );
};
